# config/default.toml

[database]
host = "localhost"
port = 5432
user = "payments_user"
password = "password"
dbname = "payments_app"
sslmode = "disable"

[payment]
payment_api_url = "https://run.mocky.io/v3/8f85da42-42cb-4fab-a51b-ea0a14153b97"

[server]
port = 9602
httpPort = 9603
